# Generated by Django 6.0.2 on 2026-02-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Église SaaS', max_length=255, verbose_name='Nom de la plateforme')),
                ('site_slogan', models.CharField(blank=True, default='Une plateforme web complète pour votre église.', max_length=500, verbose_name='Slogan')),
                ('site_description', models.TextField(blank=True, default='Paramétrez, personnalisez et publiez en quelques clics.', verbose_name='Description courte')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo de la plateforme')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact global')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
