# Generated by Codex on 2026-03-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_memberships(apps, schema_editor):
    Church = apps.get_model('church', 'Church')
    ChurchMembership = apps.get_model('church', 'ChurchMembership')

    for church in Church.objects.exclude(admin__isnull=True):
        ChurchMembership.objects.get_or_create(
            user=church.admin,
            church=church,
            defaults={'role': 'admin', 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_alter_church_cover_image_alter_church_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('staff', 'Staff'), ('secretary', 'Secrétaire')], default='staff', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='church.church', verbose_name='Église')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Membre d'église",
                'verbose_name_plural': "Membres d'église",
                'unique_together': {('user', 'church')},
            },
        ),
        migrations.AddIndex(
            model_name='churchmembership',
            index=models.Index(fields=['church', 'role', 'is_active'], name='chm_ch_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='churchmembership',
            index=models.Index(fields=['user', 'is_active'], name='chm_user_active_idx'),
        ),
        migrations.RunPython(create_memberships, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='church',
            name='admin',
        ),
    ]
