# Generated by Codex on 2026-03-17

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def default_invite_expiry():
    from django.utils import timezone
    from datetime import timedelta
    return timezone.now() + timedelta(days=7)


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_church_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('staff', 'Staff'), ('secretary', 'Secrétaire')], default='staff', max_length=20, verbose_name='Rôle')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('revoked', 'Révoquée'), ('expired', 'Expirée')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=default_invite_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_church_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Acceptée par')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='church.church', verbose_name='Église')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_church_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
            ],
            options={
                'verbose_name': "Invitation d'église",
                'verbose_name_plural': "Invitations d'église",
            },
        ),
        migrations.AddIndex(
            model_name='churchinvitation',
            index=models.Index(fields=['church', 'status'], name='ch_inv_ch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='churchinvitation',
            index=models.Index(fields=['email', 'status'], name='ch_inv_email_status_idx'),
        ),
    ]
