# Generated by Django 6.0.3 on 2026-03-20 11:27

import church.model_helpers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0019_expand_church_plan_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['name'], 'verbose_name': 'Église', 'verbose_name_plural': 'Églises'},
        ),
        migrations.AlterModelOptions(
            name='churchinvitation',
            options={'verbose_name': "Invitation d'église", 'verbose_name_plural': "Invitations d'église"},
        ),
        migrations.AlterModelOptions(
            name='churchmembership',
            options={'verbose_name': "Membre d'église", 'verbose_name_plural': "Membres d'église"},
        ),
        migrations.AlterModelOptions(
            name='contactmessagereply',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réponse au message', 'verbose_name_plural': 'Réponses aux messages'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-sermon_date'], 'verbose_name': 'Prédication', 'verbose_name_plural': 'Prédications'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Paramètres du site', 'verbose_name_plural': 'Paramètres du site'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'église"),
        ),
        migrations.AlterField(
            model_name='church',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='church',
            name='primary_color',
            field=models.CharField(default='#2c3e50', help_text='Code hexadécimal, ex: #2c3e50', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AlterField(
            model_name='church',
            name='slug',
            field=models.SlugField(help_text="Généré automatiquement à partir du nom. Ex: 'vie-nouvelle'", max_length=100, unique=True, verbose_name='Identifiant URL'),
        ),
        migrations.AlterField(
            model_name='church',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('suspended', 'Suspendue'), ('archived', 'Archivée')], db_index=True, default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='church',
            name='welcome_message',
            field=models.TextField(blank=True, help_text="Affiché sur la page d'accueil", verbose_name="Message d'accueil"),
        ),
        migrations.AlterField(
            model_name='churchinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_church_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Acceptée par'),
        ),
        migrations.AlterField(
            model_name='churchinvitation',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='churchinvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_church_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invité par'),
        ),
        migrations.AlterField(
            model_name='churchinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('staff', 'Staff'), ('secretary', 'Secrétaire')], default='staff', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='churchinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('revoked', 'Révoquée'), ('expired', 'Expirée')], db_index=True, default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='churchmembership',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='churchmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('staff', 'Staff'), ('secretary', 'Secrétaire')], default='staff', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Répondu le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('responded', 'Répondu'), ('archived', 'Archivé')], db_index=True, default='new', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='contactmessagereply',
            name='body',
            field=models.TextField(verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='contactmessagereply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_message_replies', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par'),
        ),
        migrations.AlterField(
            model_name='event',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('draft', 'Brouillon')], default='public', max_length=20, verbose_name='Visibilité'),
        ),
        migrations.AlterField(
            model_name='member',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Département/Ministère'),
        ),
        migrations.AlterField(
            model_name='member',
            name='directory_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentement donné le'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('invite', 'Invitation'), ('role', 'Changement de rôle'), ('message', 'Nouveau message'), ('event', 'Changement événement'), ('sermon', 'Changement prédication')], db_index=True, max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='page',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='page',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('draft', 'Brouillon')], default='public', max_length=20, verbose_name='Visibilité'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='bible_reference',
            field=models.CharField(blank=True, help_text='Ex: Jean 3:16', max_length=255, verbose_name='Référence biblique'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sermons', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prédicateur'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Lien vidéo (YouTube)'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('draft', 'Brouillon')], default='public', max_length=20, verbose_name='Visibilité'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="Affichée en arrière-plan sur la page d'accueil", null=True, upload_to=church.model_helpers.upload_site_asset, verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, default='Paramétrez, personnalisez et publiez en quelques clics.', verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Église SaaS', max_length=255, verbose_name='Nom de la plateforme'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_slogan',
            field=models.CharField(blank=True, default='Une plateforme web complète pour votre église.', max_length=500, verbose_name='Slogan'),
        ),
    ]
