# Generated by Django 6.0.3 on 2026-03-23 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0020_alter_church_options_alter_churchinvitation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "job_type",
                    models.CharField(
                        choices=[("send_invite_email", "Envoi email invitation")],
                        db_index=True,
                        max_length=50,
                        verbose_name="Type de tache",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("completed", "Terminee"),
                            ("failed", "Echouee"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Charge utile")),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="Nombre d'essais")),
                ("max_attempts", models.PositiveIntegerField(default=3, verbose_name="Essais maximum")),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Disponible le",
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True, verbose_name="Verrouille le")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Demarre le")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Termine le")),
                ("last_error", models.TextField(blank=True, verbose_name="Derniere erreur")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tache d'arriere-plan",
                "verbose_name_plural": "Taches d'arriere-plan",
                "ordering": ["available_at", "id"],
                "indexes": [
                    models.Index(fields=["status", "available_at"], name="bg_job_status_avail_idx"),
                    models.Index(fields=["job_type", "status"], name="bg_job_type_status_idx"),
                ],
            },
        ),
    ]
