# Generated by Django 6.0.3 on 2026-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0021_backgroundjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('send_invite_email', 'Envoi email invitation'), ('send_contact_email', 'Envoi email contact')], db_index=True, max_length=50, verbose_name='Type de tache'),
        ),
    ]
