databases:
  - name: eglise-saas-db
    plan: free
    databaseName: eglise_saas
    ipAllowList: []

services:
  - type: web
    name: eglise-saas
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn eglise_saas_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eglise-saas-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "eglise_saas_project.settings.production"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.2"
  - type: worker
    name: eglise-saas-worker
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py process_background_jobs --loop --sleep 5"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eglise-saas-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "eglise_saas_project.settings.production"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.2"
